# Project information
site_name: PHP EPUB
site_description: A PHP library for processing EPUB files, including parsing, metadata manipulation, and format conversion.
site_author: indy2kro

# Site URL (optional, useful for SEO and social sharing)
site_url: https://indy2kro.github.io/php-epub/

# Theme configuration
theme:
  name: readthedocs
  # You can customize the theme further with additional options
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Navigation structure
nav:
  - Index: index.md
  - Installation: installation.md
  - Usage:
    - Basic Usage: basic-usage.md
    - Advanced Features: advanced-usage.md
  - Classes:
    - EpubFile: epub-file.md
    - ContentManager: content-manager.md
    - Metadata: metadata.md
    - Spine: spine.md
    - Parser: parser.md
    - XmlParser: xml-parser.md
    - ZipHandler: zip-handler.md
    - Converter: converter.md
    - Converters:
      - Calibre Adapter: converters/calibre-adapter.md
      - Dompdf Adapter: converters/dompdf-adapter.md
      - TCPDF Adapter: converters/tcpdf-adapter.md

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

# Plugins
plugins:
  - search