<?php

declare(strict_types=1);

namespace PhpEpub\Converters;

use PhpEpub\ConversionException;

/**
 * A book exported as Markdown: the text, and the images it refers to.
 */
final readonly class MarkdownExport
{
    /**
     * @param string $markdown The Markdown text; images are referenced by the paths below.
     * @param array<string, string> $images Image path relative to the Markdown file ("images/cover.jpg") => bytes.
     */
    public function __construct(public string $markdown, public array $images = [])
    {
    }

    /**
     * Writes the Markdown file and an "images" folder next to it into $directory, which is created when missing.
     * Image paths are generated by MarkdownAdapter (letters, digits, ".", "_" and "-" below "images/"), so
     * nothing is written outside $directory.
     *
     * @throws ConversionException If a path is not one of those or a file or directory cannot be written.
     */
    public function writeTo(string $directory, string $fileName = 'book.md'): void
    {
        if (preg_match('/^[A-Za-z0-9][A-Za-z0-9._-]*$/', $fileName) !== 1) {
            throw new ConversionException("Invalid Markdown file name: {$fileName}");
        }

        foreach (array_keys($this->images) as $path) {
            if (preg_match('#^images/[A-Za-z0-9][A-Za-z0-9._-]*$#', (string) $path) !== 1) {
                throw new ConversionException("Invalid image path: {$path}");
            }
        }

        $directory = rtrim($directory, '/\\');
        $images = $directory . DIRECTORY_SEPARATOR . 'images';
        foreach ($this->images === [] ? [$directory] : [$directory, $images] as $folder) {
            if (! is_dir($folder) && ! @mkdir($folder, 0777, true) && ! is_dir($folder)) {
                throw new ConversionException("Failed to create the directory: {$folder}");
            }
        }

        foreach ($this->images as $path => $bytes) {
            if (@file_put_contents($directory . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, (string) $path), $bytes) === false) {
                throw new ConversionException("Failed to write the image: {$path}");
            }
        }

        if (@file_put_contents($directory . DIRECTORY_SEPARATOR . $fileName, $this->markdown) === false) {
            throw new ConversionException("Failed to write the Markdown file: {$fileName}");
        }
    }
}
