<?php

declare(strict_types=1);

namespace PhpEpub\Converters;

use Com\Tecnick\Pdf\Page\Format;
use PhpEpub\ConversionException;
use PhpEpub\Exception;
use PhpEpub\Util\FileSystemHelper;
use TCPDF;
use Throwable;

class TCPDFAdapter implements ConverterInterface
{
    /**
     * DejaVu Sans covers Latin, Greek, Cyrillic, Hebrew and Arabic, unlike the core fonts. It is
     * generated by scripts/generate-core-fonts.php, so without it the default falls back to
     * FALLBACK_FONT (Latin-1 only).
     */
    private const string DEFAULT_FONT = 'dejavusans';

    private const string FALLBACK_FONT = 'helvetica';

    private const array STYLE_TYPES = [
        'font' => 'string',
        'font_size' => 'number',
        'margin_left' => 'number',
        'margin_top' => 'number',
        'margin_right' => 'number',
        'margin_bottom' => 'number',
        'header' => 'bool',
        'footer' => 'bool',
        'paper_size' => 'string',
        'orientation' => 'string',
        'bookmarks' => 'bool',
    ];

    private const array DEFAULT_STYLES = [
        'font' => self::DEFAULT_FONT,
        'font_size' => 12,
        'margin_left' => 15,
        'margin_top' => 27,
        'margin_right' => 15,
        'margin_bottom' => 25,
        'header' => true,
        'footer' => true,
        'paper_size' => 'A4',
        'orientation' => 'portrait',
        'bookmarks' => true,
    ];

    /**
     * @var array<string, mixed>
     */
    private array $styles;

    private readonly PdfConversionOptions $options;

    /**
     * Whether the font is the default one, which may fall back to FALLBACK_FONT.
     */
    private readonly bool $defaultFont;

    /**
     * The microtime() at which the conversion in progress is over its time budget; null for no limit.
     */
    private ?float $deadline = null;

    /**
     * TCPDFAdapter constructor.
     *
     * @param array<string, mixed> $styles Optional styling parameters: font (default "dejavusans"), font_size (pt),
     *                                     margin_left, margin_top, margin_right, margin_bottom (int or float, mm),
     *                                     header, footer (bool), paper_size (e.g. "A4", "letter") and orientation
     *                                     ("portrait" or "landscape"), as in DompdfAdapter, and bookmarks (bool,
     *                                     default true: a PDF outline entry per chapter).
     *
     * @param PdfConversionOptions|null $options What to include and the limits to enforce (see there). Without
     *                                      options nothing is limited and fixed-layout books are converted as before; given options (the
     *                                      defaults include the cover, add no contents page and limit nothing) refuse fixed-layout books
     *                                      unless allowFixedLayout is true.
     *
     * @throws Exception If a style is unknown, of the wrong type or has an unusable value (such as a paper size TCPDF does not know).
     */
    public function __construct(
        array $styles = [],
        private readonly EpubDocumentLoader $loader = new EpubDocumentLoader(),
        ?PdfConversionOptions $options = null
    ) {
        // Without options the adapter behaves as it always did, fixed-layout books included.
        $this->options = $options ?? new PdfConversionOptions(allowFixedLayout: true);

        PdfStyles::validate(
            'TCPDFAdapter',
            self::STYLE_TYPES,
            $styles,
            static fn (string $size): bool => ! class_exists(Format::class) || array_key_exists(strtoupper($size), Format::FORMAT)
        );

        $this->styles = array_merge(self::DEFAULT_STYLES, $styles);
        $this->defaultFont = ! array_key_exists('font', $styles);
    }

    /**
     * Converts the EPUB content to a PDF using TCPDF.
     *
     * Every spine document is rendered in reading order, each starting on a new page,
     * and the PDF title and author are taken from the EPUB metadata.
     *
     * @param string $epubDirectory The directory containing the extracted EPUB contents.
     * @param string $outputPath The path where the converted PDF should be saved.
     *
     * @throws ConversionException If the book cannot be read, TCPDF fails (for example because the
     *                             generated fonts are missing), the PDF cannot be written, or the book is
     *                             refused by the options (fixed layout, a limit, the time budget).
     */
    public function convert(string $epubDirectory, string $outputPath): void
    {
        $this->deadline = $this->options->deadline();
        $document = $this->loader->load($epubDirectory, $this->options, $this->deadline);

        try {
            // TCPDF resolves K_PATH_FONTS itself (through Composer), whether php-epub is the root
            // project or a dependency; defining it here would point at the wrong vendor directory.
            $pdf = $this->createPdf($document)->Output('', 'S');
        } catch (Exception $exception) {
            throw $exception;
        } catch (Throwable $exception) {
            throw new ConversionException(self::failureMessage($exception), 0, $exception);
        }

        if (@file_put_contents($outputPath, $pdf) === false) {
            throw new ConversionException("Failed to write PDF: {$outputPath}");
        }
    }

    /**
     * The message for an exception of TCPDF or of its libraries, with the fix for missing font files.
     */
    private static function failureMessage(Throwable $exception): string
    {
        $message = 'TCPDF failed to render the book: ' . $exception->getMessage();

        return preg_match('/unable to read file: .*\.json/i', $exception->getMessage()) === 1
            ? $message . '. A font file is missing: check the "font" style, and generate the core fonts and DejaVu Sans with'
                . ' "php vendor/indy2kro/php-epub/scripts/generate-core-fonts.php" (see docs/installation.md)'
            : $message;
    }

    /**
     * Builds the PDF document in memory.
     */
    protected function createPdf(EpubDocument $document): TCPDF
    {
        // Inlined SVGs are written here for TCPDF (see svgImagesAsFiles()); a private directory,
        // so TCPDF can be allowed to read it without the rest of the system temp dir.
        $svgDirectory = sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'epub_pdf_' . bin2hex(random_bytes(16));
        @mkdir($svgDirectory, 0700) || throw new ConversionException("Failed to create temporary directory: {$svgDirectory}");

        try {
            return $this->fillPdf($document, array_values(array_filter([$document->directory, $svgDirectory])), $svgDirectory);
        } finally {
            (new FileSystemHelper())->deleteDirectory($svgDirectory);
        }
    }

    /**
     * @param list<string> $readableDirectories
     */
    private function fillPdf(EpubDocument $document, array $readableDirectories, string $svgDirectory): TCPDF
    {
        $author = implode(', ', $document->authors);

        $orientation = strtolower($this->stringStyle('orientation')) === 'landscape' ? 'L' : 'P';
        $pdf = $this->newPdf($orientation, strtoupper($this->stringStyle('paper_size')), $readableDirectories);
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetTitle($document->title);
        $pdf->SetAuthor($author);

        if ($this->boolStyle('header')) {
            $pdf->setHeaderData('', 0, $document->title, $author);
        } else {
            $pdf->setPrintHeader(false);
        }

        if ($this->boolStyle('footer')) {
            $pdf->setFooterData();
        } else {
            $pdf->setPrintFooter(false);
        }

        $pdf->SetMargins($this->numberStyle('margin_left'), $this->numberStyle('margin_top'), $this->numberStyle('margin_right'));
        $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
        $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
        $pdf->SetAutoPageBreak(true, $this->numberStyle('margin_bottom'));
        $this->selectFont($pdf);

        if ($document->rightToLeft) {
            $pdf->setRTL(true);
        }

        if ($document->coverImage !== '') {
            $this->addPage($pdf);
            if ($this->boolStyle('bookmarks')) {
                $pdf->Bookmark('Cover', 0, 0);
            }

            // Scaled to fit the area inside the margins, centred.
            $left = $this->numberStyle('margin_left');
            $top = $this->numberStyle('margin_top');
            $width = $pdf->getPageWidth() - $left - $this->numberStyle('margin_right');
            $height = $pdf->getPageHeight() - $top - $this->numberStyle('margin_bottom');
            $pdf->Image($document->coverImage, $left, $top, $width, $height, '', '', '', true, 300, '', false, false, 0, 'CM');
        }

        if ($document->contents !== '') {
            $this->addPage($pdf);
            if ($this->boolStyle('bookmarks')) {
                $pdf->Bookmark('Contents', 0, 0);
            }

            $pdf->writeHTML($this->chapterHtml($document, $document->contents), true, false, true, false, '');
        }

        foreach ($document->chapters as $index => $chapter) {
            $this->options->assertWithinBudget($this->deadline);
            $this->addPage($pdf);
            if ($this->boolStyle('bookmarks')) {
                $title = $document->chapterTitles[$index] ?? '';
                $pdf->Bookmark($title !== '' ? $title : 'Chapter ' . ($index + 1), 0, 0);
            }

            $pdf->writeHTML($this->chapterHtml($document, $this->svgImagesAsFiles($chapter, $svgDirectory)), true, false, true, false, '');
        }

        if ($document->chapters === [] && $document->coverImage === '' && $document->contents === '') {
            $this->addPage($pdf);
        }

        return $pdf;
    }

    /**
     * Adds a page, of the custom size in mm when the options have one (else of the paper_size style the
     * document was created with).
     */
    private function addPage(TCPDF $pdf): void
    {
        $custom = $this->options->customPageSize();
        if ($custom === null) {
            $pdf->AddPage();

            return;
        }

        $pdf->AddPage(strtolower($this->stringStyle('orientation')) === 'landscape' ? 'L' : 'P', $custom);
    }

    /**
     * Selects the font. The default font falls back to FALLBACK_FONT when its definition has not been
     * generated (a project that ran scripts/generate-core-fonts.php before DejaVu Sans was added to it);
     * a font that was asked for never falls back.
     */
    private function selectFont(TCPDF $pdf): void
    {
        $size = $this->numberStyle('font_size');

        try {
            $pdf->SetFont($this->stringStyle('font'), '', $size);
        } catch (Throwable $exception) {
            if (! $this->defaultFont) {
                throw $exception;
            }

            $pdf->SetFont(self::FALLBACK_FONT, '', $size);
        }
    }

    /**
     * Creates the TCPDF instance (in mm) that createPdf() fills.
     *
     * @param string $orientation "P" or "L".
     * @param string $format A TCPDF page format, e.g. "A4" or "LETTER".
     * @param list<string> $readableDirectories The only directories (besides TCPDF's own files) TCPDF may read.
     */
    protected function newPdf(string $orientation, string $format, array $readableDirectories = []): TCPDF
    {
        return new ConfinedTcpdf($orientation, $format, $readableDirectories);
    }

    /**
     * A chapter as passed to writeHTML(): TCPDF takes CSS from <style> elements in that HTML,
     * so the book's styles are prepended to every chapter.
     */
    protected function chapterHtml(EpubDocument $document, string $chapter): string
    {
        return ($document->styles === [] ? '' : '<style>' . EpubDocument::styleSheet($document->styles) . '</style>') . $chapter;
    }

    /**
     * TCPDF only renders an <img> as SVG when its source ends in ".svg", so the sanitised SVG
     * data: URIs of EpubDocumentLoader are written to temporary files for the conversion.
     *
     * @param string $directory The private directory createPdf() deletes afterwards.
     */
    private function svgImagesAsFiles(string $html, string $directory): string
    {
        return (string) preg_replace_callback(
            '#\bsrc="data:image/svg\+xml;base64,([A-Za-z0-9+/=]+)"#',
            static function (array $match) use ($directory): string {
                $file = $directory . DIRECTORY_SEPARATOR . bin2hex(random_bytes(8)) . '.svg';

                return @file_put_contents($file, (string) base64_decode($match[1], true)) !== false
                    ? 'src="' . htmlspecialchars(str_replace('\\', '/', $file)) . '"'
                    : $match[0];
            },
            $html
        );
    }

    private function stringStyle(string $name): string
    {
        $value = $this->styles[$name] ?? null;

        return is_string($value) ? $value : (string) self::DEFAULT_STYLES[$name];
    }

    private function numberStyle(string $name): int|float
    {
        $value = $this->styles[$name] ?? null;

        return is_int($value) || is_float($value) ? $value : (int) self::DEFAULT_STYLES[$name];
    }

    private function boolStyle(string $name): bool
    {
        $value = $this->styles[$name] ?? null;

        return is_bool($value) ? $value : (bool) self::DEFAULT_STYLES[$name];
    }
}
